### ISSUE TITLE
sci dies after checking sample sheet

### ISSUE THREAD

**Issue by cuperusj** [bbi-lab/bbi-sci#17]
demux was completed successfully- all dependencies have been installed, starting bbi-sci it does 100% check of sample sheet then ends. I've also tried the -resume with the same problem. Heres the logs:

Sep-19 11:08:46.631 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.07.1
Sep-19 11:08:46.665 [main] DEBUG nextflow.scm.AssetManager - Listing projects in folder: /net/fields/vol1/home/cuperusj/.nextflow/assets
Sep-19 11:08:47.588 [main] DEBUG nextflow.scm.AssetManager - Git config: /net/fields/vol1/home/cuperusj/.nextflow/assets/bbi-lab/bbi-sci/.git/config; branch: master; remote: origin; url: https://github.com/bbi-lab/bbi-sci.git
Sep-19 11:08:47.609 [main] DEBUG nextflow.scm.AssetManager - Git config: /net/fields/vol1/home/cuperusj/.nextflow/assets/bbi-lab/bbi-sci/.git/config; branch: master; remote: origin; url: https://github.com/bbi-lab/bbi-sci.git
Sep-19 11:08:47.783 [main] WARN  org.eclipse.jgit.util.FS - Exception caught during execution of command '[git, config, --system, --edit]' in '/net/gs/vol3/software/modules-sw/git/2.18.0/Linux/CentOS7/x86_64/bin', return code '128', error message 'fatal: Invalid path '/net/gs/vol3/software/modules-sw/git/2.18.0/Linux/CentOS7/x86_64/etc': No such file or directory
'
Sep-19 11:08:47.859 [main] DEBUG nextflow.scm.AssetManager - Git config: /net/fields/vol1/home/cuperusj/.nextflow/assets/bbi-lab/bbi-sci/.git/config; branch: master; remote: origin; url: https://github.com/bbi-lab/bbi-sci.git
Sep-19 11:08:47.859 [main] INFO  nextflow.cli.CmdRun - Launching `bbi-lab/bbi-sci` [gigantic_dubinsky] - revision: 93a2a3a257 [master]
Sep-19 11:08:48.467 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /net/fields/vol1/home/cuperusj/.nextflow/assets/bbi-lab/bbi-sci/nextflow.config
Sep-19 11:08:48.471 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /net/fields/vol1/home/cuperusj/Arabidopsis_sci/Josh.config
Sep-19 11:08:48.471 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /net/fields/vol1/home/cuperusj/.nextflow/assets/bbi-lab/bbi-sci/nextflow.config
Sep-19 11:08:48.472 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /net/fields/vol1/home/cuperusj/Arabidopsis_sci/Josh.config
Sep-19 11:08:48.482 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Sep-19 11:08:48.736 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Sep-19 11:08:48.846 [main] DEBUG nextflow.Session - Session uuid: 5915a511-e3f7-4cb2-813c-608a4bf85029
Sep-19 11:08:48.846 [main] DEBUG nextflow.Session - Run name: gigantic_dubinsky
Sep-19 11:08:48.847 [main] DEBUG nextflow.Session - Executor pool size: 5
Sep-19 11:08:48.896 [main] DEBUG nextflow.cli.CmdRun -
  Version: 20.07.1 build 5412
  Created: 24-07-2020 15:18 UTC (08:18 PDT)
  System: Linux 3.10.0-1062.18.1.el7.x86_64
  Runtime: Groovy 2.5.11 on OpenJDK 64-Bit Server VM 14.0.2+12
  Encoding: UTF-8 (UTF-8)
  Process: 43104@t006.grid.gs.washington.edu [10.250.0.6]
  CPUs: 5 - Mem: 20 GB (711.6 MB) - Swap: 8 GB (8 GB)
Sep-19 11:08:48.953 [main] DEBUG nextflow.Session - Work-dir: /net/fields/vol1/home/cuperusj/Arabidopsis_sci/work [nfs]
Sep-19 11:08:49.021 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Sep-19 11:08:49.025 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Sep-19 11:08:49.595 [main] DEBUG nextflow.Session - Session start invoked
Sep-19 11:08:50.908 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Sep-19 11:08:50.920 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: zip_up_sample_stats, process_hashes, generate_qc_metrics, merge_bams, remove_dups_assign_genes, check_sample_sheet, trim_fastqs, generate_dashboard, combine_logs, gather_info, run_scrublet, make_cds, align_reads, apply_garnett, make_matrix, calc_cell_totals, merge_assignment, collapse_collision, split_bam, reformat_scrub, zip_up_log_data, sort_and_filter, count_umis_by_sample, finish_log
Sep-19 11:08:51.099 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:check_sample_sheet` matches process check_sample_sheet
Sep-19 11:08:51.108 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.109 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.120 [main] DEBUG nextflow.executor.Executor - [warm up] executor > sge
Sep-19 11:08:51.132 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'sge' > capacity: 100; pollInterval: 5s; dumpInterval: 5m
Sep-19 11:08:51.137 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'sge' > queue-stat-interval: 1m
Sep-19 11:08:51.362 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /net/fields/vol1/home/cuperusj/Arabidopsis_sci/; pattern: *.fastq.gz; options: [:]
Sep-19 11:08:51.387 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:trim_fastqs` matches process trim_fastqs
Sep-19 11:08:51.390 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.390 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.445 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:gather_info` matches process gather_info
Sep-19 11:08:51.447 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.447 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.512 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:process_hashes` matches process process_hashes
Sep-19 11:08:51.514 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.514 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.530 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:align_reads` matches process align_reads
Sep-19 11:08:51.532 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.532 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.545 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:sort_and_filter` matches process sort_and_filter
Sep-19 11:08:51.546 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.546 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.561 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:combine_logs` matches process combine_logs
Sep-19 11:08:51.563 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.563 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.590 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:merge_bams` matches process merge_bams
Sep-19 11:08:51.592 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.592 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.612 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:split_bam` matches process split_bam
Sep-19 11:08:51.613 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.613 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.621 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:remove_dups_assign_genes` matches process remove_dups_assign_genes
Sep-19 11:08:51.623 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.623 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.640 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:merge_assignment` matches process merge_assignment
Sep-19 11:08:51.641 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.641 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.682 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:count_umis_by_sample` matches process count_umis_by_sample
Sep-19 11:08:51.683 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.683 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.694 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:make_matrix` matches process make_matrix
Sep-19 11:08:51.695 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.695 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.702 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:make_cds` matches process make_cds
Sep-19 11:08:51.703 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.703 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.712 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:apply_garnett` matches process apply_garnett
Sep-19 11:08:51.713 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.713 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.724 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:run_scrublet` matches process run_scrublet
Sep-19 11:08:51.726 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.726 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.742 [Actor Thread 3] INFO  nextflow.processor.TaskProcessor - [86/d0b547] Cached process > check_sample_sheet
Sep-19 11:08:51.744 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:reformat_scrub` matches process reformat_scrub
Sep-19 11:08:51.747 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.747 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.808 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:generate_qc_metrics` matches process generate_qc_metrics
Sep-19 11:08:51.808 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.809 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.824 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:zip_up_sample_stats` matches process zip_up_sample_stats
Sep-19 11:08:51.825 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.825 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.832 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:calc_cell_totals` matches process calc_cell_totals
Sep-19 11:08:51.832 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.833 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.838 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:collapse_collision` matches process collapse_collision
Sep-19 11:08:51.839 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.839 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.846 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:generate_dashboard` matches process generate_dashboard
Sep-19 11:08:51.847 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.847 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.855 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:finish_log` matches process finish_log
Sep-19 11:08:51.855 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.855 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.863 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:zip_up_log_data` matches process zip_up_log_data
Sep-19 11:08:51.863 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Sep-19 11:08:51.863 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Sep-19 11:08:51.868 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Sep-19 11:08:51.869 [main] DEBUG nextflow.Session - Session await
Sep-19 11:08:51.869 [main] DEBUG nextflow.Session - Session await > all process finished
Sep-19 11:08:56.142 [main] DEBUG nextflow.Session - Session await > all barriers passed
Sep-19 11:08:56.152 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=1; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=14ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Sep-19 11:08:56.370 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Sep-19 11:08:56.448 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by hpliner** [comment]
Hey Josh, I just had a peak at your config file - looks like you're not pointing to your demux_out folder where your fastqs are. If the pipe can't find any fastqs that match the samplesheet it'll just end thinking it's done it all! Try changing `params.demux_out = "/net/fields/vol1/home/cuperusj/Arabidopsis_sci"` to `params.demux_out = "/net/fields/vol1/home/cuperusj/Arabidopsis_sci/demux_out"` and let me know if that fixes it

**Comment by cuperusj** [comment]
ok ill give that a shot, on second glance demux did not finish properly- with this error-

[4c/d52fcd] process > seg_sample_fastqs1 (1) [100%] 1 of 1 ✔
[48/6e418e] process > demux_dash1            [100%] 1 of 1, failed: 1 ✘
[-        ] process > seg_sample_fastqs2     -
[-        ] process > recombine_fastqs       -
[-        ] process > recombine_csvs         -
[-        ] process > recombine_jsons        -
[-        ] process > demux_dash             -
[-        ] process > run_recovery           -
[-        ] process > sum_recovery           -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'demux_dash1'

Caused by:
  Process `demux_dash1` terminated with an error exit status (127)

Command executed:

  mkdir demux_dash
  cp -R /net/fields/vol1/home/cuperusj/.nextflow/assets/bbi-lab/bbi-dmux/bin/skeleton_dash/* demux_dash/
  generate_html.R         "." --p7_rows "0" --p5_cols "0" --p7_wells "A1 A1 A1 A1 A1 A1 A1 A1 A2 A2 A2 A2 A2 A2 A2 A2 A3 A3 A3 A3 A3 A3 A3 A3 A4 A4 A4 A4 A4 A4 A4 A4 D1 D
1 D1 D1 D1 D1 D1 D1 D2 D2 D2 D2 D2 D2 D2 D2 D3 D3 D3 D3 D3 D3 D3 D3 D4 D4 D4 D4 D4 D4 D4 D4 D5 D5 D5 D5 D5 D5 D5 D5 D6 D6 D6 D6 D6 D6 D6 D6" --p5_wells "A3 B3 C3 D3 E3 F3
 G3 H3 A4 B4 C4 D4 E4 F4 G4 H4 A5 B5 C5 D5 E5 F5 G5 H5 A6 B6 C6 D6 E6 F6 G6 H6 A1 B1 C1 D1 E1 F1 G1 H1 A2 B2 C2 D2 E2 F2 G2 H2 A3 B3 C3 D3 E3 F3 G3 H3 A4 B4 C4 D4 E4 F4 G
4 H4 A5 B5 C5 D5 E5 F5 G5 H5 A6 B6 C6 D6 E6 F6 G6 H6" --level "2" --project_name "Arabidopsis_sci" --sample_sheet "good_sample_sheet.csv"

Command exit status:
  127

Command output:
  (empty)

Command error:
  /usr/bin/env: Rscript: No such file or directory

Work dir:
  /net/fields/vol1/home/cuperusj/Arabidopsis_sci/work/48/6e418e3f74e680a397c7c4e7e0b261

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by aishwaryagogate** [comment]
I'm going to close the issue, reply/reopen if you have further problems.
