### ISSUE TITLE
process_hashes requires installation of scipy

### ISSUE THREAD

**Issue by atresen** [bbi-lab/bbi-sci#19]
With centos7, the installation instructions should require users to install scipy if they want to process hashes.

![Screen Shot 2020-09-25 at 10 02 42 AM](https://user-images.githubusercontent.com/31747459/94462611-a6b86780-0170-11eb-987d-38b098cdd608.png)

**Comment by aishwaryagogate** [comment]
Updated git/2.19.1 to git/2.18.0
Added matplotlib & scipy installation info
